version: '3.7'

services:
  backend:
    build:
        context: ./simple-api-student-main
    networks:
        - app-network
    depends_on:
        - database
    container_name: backend-api

  database:
    build:
        context: ./db
    networks:
        - app-network
    container_name: postgres-epf

  httpd:
    build:
        context: ./front
    ports:
        - "80:80"
    networks:
        - app-network
    depends_on:
        - backend
        - database

networks:
  app-network:
